name: publish

on:
    release:
        types: [created]

permissions:
    id-token: write
    contents: read

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Node environment
              uses: actions/setup-node@v6
              env:
                  NPM_CONFIG_PROVENANCE: true
              with:
                  node-version: 25
                  registry-url: https://registry.npmjs.org

            - name: Install latest npm
              run: npm install -g npm@latest

            - name: Install dependencies
              run: npm i

            - name: Build project
              run: npm run build

            - name: Publish Package
              run: npm publish --provenance --access public
